import starterOne from "../assets/plansImg/istockphoto-1346163635-612x612.webp";
export const plans = [
  {
    id: 1,
    planType: "Starter",
    planImg: starterOne,
    minimuimPlan: "$55 Minimum",
    maximiumPlan: "$1,000 Maximum",
    investSpan:{
        moneyback: "Money Back?",
        yesAns:"yes!!!",
        EarnPercent: "Earn 5% after 2days.",
        duration: "Duration: 2",
    },
    Button:"Get Started",
  },
  {
    id: 2,
    planType: "Basic",
    planImg: starterOne,
    minimuimPlan: "$1,000 Minimum",
    maximiumPlan: "$3,999 Maximum",
    investSpan:{
        moneyback: "Money Back?",
        yesAns:"yes!!!",
        EarnPercent: "Earn 5% after 2days.",
        duration: "Duration: 2",
    },
    Button:"Get Started",
  },
  {
    id: 3,
    planType: "Bronze",
    planImg: starterOne,
    minimuimPlan: "$4,000 Minimum",
    maximiumPlan: "$18,000 Maximum",
    investSpan:{
        moneyback: "Money Back?",
        yesAns:"yes!!!",
        EarnPercent: "Earn 5% after 2days.",
        duration: "Duration: 2",
    },
    Button:"Get Started",
  },
  {
    id: 4,
    planType: "Silver",
    planImg: starterOne,
    minimuimPlan: "$1,000 Minimum",
    maximiumPlan: "$3, Maximum",
    investSpan:{
        moneyback: "Money Back?",
        yesAns:"yes!!!",
        EarnPercent: "Earn 5% after 2days.",
        duration: "Duration: 2",
    },
    Button:"Get Started",
  },
  {
    id: 5,
    planType: "Gold",
    planImg: starterOne,
    minimuimPlan: "$4,000 Minimum",
    maximiumPlan: "$18,000 Maximum",
    investSpan:{
        moneyback: "Money Back?",
        yesAns:"yes!!!",
        EarnPercent: "Earn 5% after 2days.",
        duration: "Duration: 2",
    },
    Button:"Get Started",
  },
  {
    id: 6,
    planType: "Diamond",
    planImg: starterOne,
    minimuimPlan: "$18,000 Minimum",
    maximiumPlan: "$80,000 Maximum",
    investSpan:{
        moneyback: "Money Back?",
        yesAns: "yes!!!",
        EarnPercent: "Earn 5% after 2days.",
        duration: "Duration: 2",
    },
    Button:"Get Started",
  },
  {
    id: 7,
    planType: "Super Z3",
    planImg: starterOne,
    minimuimPlan: "$9,000 Minimum",
    maximiumPlan: "$9,000 Maximum",
    investSpan:{
        moneyback: "Money Back?",
        yesAns:"yes!!!",
        EarnPercent: "Earn 5% after 2days.",
        duration: "Duration: 2",
    },
    Button:"Get Started",
  },
  {
    id: 8,
    planType: "Super King Z3",
    planImg: starterOne,
    minimuimPlan: "$12,000 Minimum",
    maximiumPlan: "$12,000 Maximum",
    investSpan:{
        moneyback: "Money Back?",
        yesAns:"yes!!!",
        EarnPercent: "Earn 5% after 2days.",
        duration: "Duration: 2",
    },
    Button:"Get Started",
  },
  {
    id: 9,
    planType: "Promo - 1",
    planImg: starterOne,
    minimuimPlan: "$1,000 Minimum",
    maximiumPlan: "$1,000 Maximum",
    investSpan:{
        moneyback: "Money Back?",
        yesAns:"yes!!!",
        EarnPercent: "Earn 5% after 2days.",
        duration: "Duration: 2",
    },
    Button:"Get Started",
  },
  {
    id: 10,
    planType: "Promo - 2",
    planImg: starterOne,
    minimuimPlan: "$1,500 Minimum",
    maximiumPlan: "$1,500 Maximum",
    investSpan:{
        moneyback: "Money Back?",
        yesAns:"yes!!!",
        EarnPercent: "Earn 5% after 2days.",
        duration: "Duration: 2",
    },
    Button:"Get Started",
  },
  {
    id: 11,
    planType: "Promo - 3",
    planImg: starterOne,
    minimuimPlan: "$3,000 Minimum",
    maximiumPlan: "$3,000 Maximum",
    investSpan:{
        moneyback: "Money Back?",
        yesAns:"yes!!!",
        EarnPercent: "Earn 5% after 2days.",
        duration: "Duration: 2",
    },
    Button:"Get Started",
  },
  {
    id: 12,
    planType: "Retirement Plan",
    planImg: starterOne,
    minimuimPlan: "$30,000 Minimum",
    maximiumPlan: "$30,000 Maximum",
    investSpan:{
        moneyback: "Money Back?",
        yesAns:"yes!!!",
        EarnPercent: "Earn 5% after 2days.",
        duration: "Duration: 2",
    },
    Button:"Get Started",
  },
];
